sudo: required

services:
  - docker

before_install:
  - docker build -t comet .

script:
  - docker run -v $TRAVIS_BUILD_DIR:/analysis comet /bin/bash -c "source activate comet && cd /analysis && snakemake"
