name: root
dependencies:
- numpy=1.10.4=py35_1
- openblas=0.2.14=4
- openssl=1.0.2g=0
- pandas=0.17.0
- numexpr=2.4
- matplotlib=1.4.3
- scikit-learn=0.17.0
- pip=8.1.1
- pip:
  - snakemake==3.6.1
  - runipy==0.1.5
  - ipyparallel==5.0.1
  - ipython-genutils==0.1.0
  - itsdangerous==0.24
  - jupyterhub==0.5.0
  - jupyter==1.0.0
  - "--editable=git+https://github.com/renatopp/liac-arff.git@03394074deca70db2ff748bbccbbfe284254c54f#egg=liac-arff-2.1.1dev"
  - "--editable=git+https://github.com/openml/openml-python.git@26686b0dda5b08776ef59e8637c5e3cd81dfca00#egg=openml-0.2.1"
